trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

- script: |

    echo "$secrets.SSH_PRIVATE_KEY" > ssh_key
    chmod 600 ssh_key
    
    # SSH into the VM and execute commands
    ssh -i ssh_key azureuser@20.102.109.45 "sudo apt update -y && sudo apt install apache2 -y && sudo systemctl start apache2 && sudo bash -c 'echo your first web server > /var/www/html/index.html'"
  displayName: 'SSH into VM and execute commands'

