trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployToVM
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'
  - script: |
      echo "$secrets.SSH_PRIVATE_KEY" | tr -d '\r' > ssh_key
      chmod 600 ssh_key
      
      # SSH into the VM and execute commands
      ssh -o StrictHostKeyChecking=no -i ssh_key azureuser@20.102.109.45 "sudo apt update -y && sudo apt install apache2 -y && sudo systemctl start apache2 && sudo bash -c 'echo your first web server > /var/www/html/index.html'"
    displayName: 'SSH into VM and execute commands'
