trigger:
- main  # Assuming your main branch is named 'main'

pr:
- '*'

pool:
  name: 'YourSelfHostedAgentPool'  # Replace with the name of your self-hosted agent pool

jobs:
- job: DeployToVM
  displayName: 'Deploy to VM'
  pool:
    vmImage: 'your-self-hosted-agent'  # Replace with the name of your self-hosted agent

  steps:
  - script: |
      # Install SSH client
      sudo apt update -y
      sudo apt install openssh-client -y
      
      # Set up SSH private key
      echo "$SSH_PRIVATE_KEY" > ssh_key
      chmod 600 ssh_key
      
      # SSH into the VM and execute commands
      ssh -i ssh_key azureuser@52.172.88.62 "sudo apt update -y && sudo apt install apache2 -y && sudo systemctl start apache2 && sudo bash -c 'echo your first web server > /var/www/html/index.html'"
    displayName: 'SSH into VM and execute commands'

  # Clean up the SSH key
  - script: |
      rm ssh_key
    displayName: 'Clean up SSH Key'
